### ISSUE TITLE
Ranking incorrectly ignores omitted games

### ISSUE THREAD

**Issue by ulmont** [SASEliminator/issues#11] opened 2017-02-06 22:06 UTC
Every omitted game should be scored as a loss for ranking purposes.  Right now eliminator ignores unpicked games, leading to everyone with 3-0 playoff eliminator picks ranked above everyone who went 3-1.

![image](https://cloud.githubusercontent.com/assets/25596585/22668378/2b129e1e-ec86-11e6-873a-1c25850b3336.png)

**Comment by elfurbe** [comment] 2017-02-06 22:38
Nope, not incorrect. Leaderboards are ordered by wins and all of these people are ranked exactly the same. They're all tied for 3rd as you can see in the left hand column where they're all "3"s. So they're at the top of the list of 3rd placers, who cares, it's all 3rd. 3rd is 3rd. I'm in there for 3rd, you're in there for 3rd. I've got a loss, you don't have a loss, we're all 3rd place. Maybe I code up a storm and I list you at the bottom of 3rd place. You're still ranked 3rd. I'm still ranked 3rd. Maybe I sprinkle the no-pickers throughout the list randomly. You're still ranked 3rd. I'm still ranked 3rd. We're all 3rd and we should all be ashamed of not being 1st, Mission Accomplished.

This is essentially a duplicate of #4, except in reverse. I fixed the rankings to ignore losses and only count wins when I closed that ticket. It used to be the case that all you no-pickers would have been 3rd and I'dve been in 4th with the other 1-lossers, which was super wrong. 3 wins is 3 wins now, that was the fix that needed to be applied and it has been.

**Closed as completed by elfurbe** 2017-02-06 22:38 UTC
Labels: invalid, wontfix

**Comment by ulmont** [comment] 2017-02-06 22:42
The only reason I am 3-0 and not 3-1 is I ran out of teams, which shows you that a skipped pick is a loss.

**Comment by qwijib0** [comment] 2017-02-06 22:52
I agree.  That's why everybody is ranked 3rd, they all have 3 wins and one no-pick OR loss, which are effectively the same in the standings.

**Comment by elfurbe** [comment] 2017-02-06 23:19
We've explained how we score and why that means this is not a bug. We like this scoring system, it's how we want it to be. Learn to love your third place finish.

Still closed, will not re-open, wontfix, notbug, etc.
